models/OpcionMenu.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "opcion_menu".
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $estado
 * @property integer $orden
 *
 * @property ItemMenu[] $itemMenus
 * @property OpcionHasRol[] $opcionHasRols
 */
class OpcionMenu extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'opcion_menu';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['estado', 'orden'], 'integer'],
            [['nombre'], 'string', 'max' => 95],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'estado' => 'Estado',
            'orden' => 'Orden',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItemMenus()
    {
        return $this->hasMany(ItemMenu::className(), ['id_opcion' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOpcionHasRols()
    {
        return $this->hasMany(OpcionHasRol::className(), ['id_opcion' => 'id']);
    }
}

controllers/OpcionmenuController.php
<?php

namespace app\controllers;

use Yii;
use app\models\OpcionMenu;
use app\models\OpcionMenuSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OpcionmenuController implements the CRUD actions for OpcionMenu model.
 */
class OpcionmenuController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all OpcionMenu models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OpcionMenuSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single OpcionMenu model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new OpcionMenu model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new OpcionMenu();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing OpcionMenu model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing OpcionMenu model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the OpcionMenu model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return OpcionMenu the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = OpcionMenu::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/opcionmenu/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\OpcionMenu */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="opcion-menu-form">

    <?php $form = ActiveForm::begin(); ?>
	
	<div class="card ">
      	<!-- Default card contents -->
		<div class="card-heading card-header-primary">Opción Menú</div>
		<div class="card-body">

		    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

		    <div class="form-group">
		        <?= Html::submitButton($model->isNewRecord ? 'Crear' : 'Actualizar', ['class' => $model->isNewRecord ? 'btn btn-default' : 'btn btn-default']) ?>
				<?= Html::a('<i class="fa fa-fw fa-reply"></i> Volver', ['opcionmenu/index'], ['class' => 'btn btn-primary btn-sm']) ?>
		    </div>
		</div>
	</div>

    <?php ActiveForm::end(); ?>

</div>

views/opcionmenu/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\OpcionMenuSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="opcion-menu-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nombre') ?>

    <?= $form->field($model, 'estado') ?>

    <?= $form->field($model, 'orden') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/opcionmenu/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\OpcionMenu */

$this->title = 'Create Opcion Menu';
$this->params['breadcrumbs'][] = ['label' => 'Opcion Menus', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="opcion-menu-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/opcionmenu/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\OpcionMenuSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Opcion Menus';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="opcion-menu-index">

   
    <div class="card card-primary">
        <!-- Default card contents -->
        <div class="card-header card-header-primary">OPCIÓN MENÚ</div>
        <div class="card-body">
    
            <p>
                <?= Html::a("<i class='fa fa-check'></i> &nbsp;Create Opción Menú", ['create'], ['class' => 'btn btn-dafult']) ?>
            </p>

            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    'id',
                    'nombre',

                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{view}{update}',
                        'buttons' => [
                            
                            'view' => function ($url, $model, $key) {
                                // return Html::a('My Action', ['my-action', 'id'=>$model->id]);
                                return Html::a('<span class="fas fa-eye"></span>', ['opcionmenu/view', 'id'=>$model->id] );
                            },

                            'update' => function ($url, $model, $key) {
                                // return Html::a('My Action', ['my-action', 'id'=>$model->id]);
                                return Html::a('<span class="fas fa-user-edit"></span>', ['opcionmenu/update', 'id'=>$model->id] );
                            },
                        ]
                    ],  
                ],
            ]); ?>
        </div>
    </div>
</div>

views/opcionmenu/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\OpcionMenu */

$this->title = 'Update Opcion Menu: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Opcion Menus', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="opcion-menu-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/opcionmenu/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\OpcionMenu */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Opcion Menus', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="opcion-menu-view">
    
    <div class="card ">
        <!-- Default card contents -->
        <div class="card-header card-header-primary">Opción Menú</div>
        <div class="card-body">
            <p>
                
                <?= Html::a('<i class="fa fa-fw fa-edit"></i> Actualizar información', ['update', 'id' => $model->id], ['class' => 'btn btn-default']) ?>
                <?= Html::a('<i class="fa fa-fw fa-reply"></i> Volver', ['opcionmenu/index'], ['class' => 'btn btn-primary btn-sm']) ?>
            </p>

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'id',
                    'nombre',
                ],
            ]) ?>
        </div>
    </div>
</div>