models/Users.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "users".
 *
 * @property integer $id
 * @property string $username
 * @property string $email
 * @property string $password
 * @property string $authKey
 * @property string $accessToken
 * @property integer $activate
 * @property integer $role
 * @property integer $cargo_id
 * @property string $nombres
 * @property string $apellidos
 * @property string $foto
 */
class Users extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombres', 'apellidos', 'numeroIdentificacion' ,'username','role' ,'password'], 'required'],
            [['activate','numeroIdentificacion'], 'integer'],
            [['foto','role'], 'string'],
            [['username'], 'string', 'max' => 50],
            [['email'], 'string', 'max' => 80],
            [['email'], 'email'],
            [['password', 'authKey', 'accessToken'], 'string', 'max' => 250],
            [['direccion'], 'string', 'max' => 150],
            // ['password', 'match', 'pattern' => "/^.{6,20}$/", 'message' => 'Mínimo 6 y máximo 16 caracteres'],
            [['nombres', 'apellidos'], 'string', 'max' => 60],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'email' => 'Email',
            'password' => 'Password',
            'authKey' => 'Auth Key',
            'accessToken' => 'Access Token',
            'activate' => 'Activate',
            'role' => 'Role',
            'nombres' => 'Nombres',
            'apellidos' => 'Apellidos',
            'foto' => 'Foto',
        ];
    }

    public function getRol()
    {
        return $this->hasOne(Rol::className(), ['id' => 'role']);
    }

    

    

    
    

    public function email_existe($attribute, $params)
    {
    
    //Buscar el email en la tabla
    $table = Users::find()->where("email=:email", [":email" => $this->email]);
    
    //Si el email existe mostrar el error
    if ($table->count() == 1)
    {
      $this->addError($attribute, "El email seleccionado existe");
    }
      }
    
      public function username_existe($attribute, $params)
      {
    //Buscar el username en la tabla
    $table = Users::find()->where("username=:username", [":username" => $this->username]);
    
    //Si el username existe mostrar el error
    if ($table->count() == 1)
    {
                  $this->addError($attribute, "El usuario seleccionado existe");
    }
      }
    
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\Response;
use app\models\FormRegister; 
use app\models\Users; 
use app\models\AccesosDirectos; 
use yii\widgets\ActiveForm;
use app\models\User;
use app\models\Rol;
use yii\db\Query;
use yii\data\Pagination;
use app\models\FormSearch;
use app\models\HistoriasClinicas;
use app\models\OpcionMenu;
use app\models\ItemMenu;
use app\models\SubitemMenu;
use app\models\Menuperfil;
use app\models\Pacientes;
use yii\helpers\Url;


use yii\helpers\Html;


class SiteController extends Controller
{
    // public function behaviors()
    // {
    //     return [
    //         //Controla el modo en que se accede a las acciones, en este ejemplo a la acción logout
    //         //sólo se puede acceder a través del método post
    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'logout' => ['post','get'],
    //             ],
    //         ],
    //     ];
    // }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    

    public function actionIndex()
    {   

        if (!Yii::$app->user->isGuest) {
            # code...
        

            $userIdentity = Users::findOne(yii::$app->user->identity->id);
            // CONSULTAS ACCESOS DIRECTOS
                $query = new Query();
                $connection = Yii::$app->db;
                $accesosDirectos = array();
                $arrayTapas = AccesosDirectos::find()
                                    ->where(['idRol' => yii::$app->user->identity->role ])
                                    ->all();
                foreach ($arrayTapas as $a) {
                    array_push($accesosDirectos, $a->numerotapa);
                }
                $roles = Rol::find()->all();
                
            $idUsuario =  Yii::$app->user->identity->id;

            // se instancia la Clase Query.
            $query = new Query();
            $connection = Yii::$app->db;

            $query = $connection->createCommand('SELECT count(*) as total
                                                from    peliculas
                                               ');
            $peliculas = $query->queryOne();                       


            // echo "<pre>";
            // print_r($estadistica2);
            // echo "<br>";
            // print_r($estadisticanum2);
            // die;


            return $this->render('index',[
                'userIdentity' => $userIdentity,
                'accesosDirectos' => $accesosDirectos,
                'peliculas' => $peliculas,               

            ]);


        }else{

            return $this->redirect(["site/login"]);
            
        }

    }



    
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->redirect(["site/index"]);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {

             return $this->redirect(["site/index"]);

        } else {
             return $this->render('login', [
                 'model' => $model,
             ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionUser(){
        return $this->render("user");
    }

    public function actionAdmin(){
        return $this->render("admin");
    }

    private function randKey($str='', $long=0){
        $key = null;
        $str = str_split($str);
        $start = 0;
        $limit = count($str)-1;

        for($x=0; $x<$long; $x++)
        {
            $key .= $str[rand($start, $limit)];
        }

        return $key;
    }

    public function actionConfirm(){

        $table = new Users;

        if (Yii::$app->request->get())
        {
            //Obtenemos el valor de los parámetros get
            $id = Html::encode($_GET["id"]);
            $authKey = $_GET["authKey"];
        
            if ((int) $id)
            {
                //Realizamos la consulta para obtener el registro
                $model = $table
                ->find()
                ->where("id=:id", [":id" => $id])
                ->andWhere("authKey=:authKey", [":authKey" => $authKey]);
      
                //Si el registro existe
                if ($model->count() == 1)
                {
                    $activar = Users::findOne($id);
                    $activar->activate = 1;

                    if ($activar->update())
                    {
                        echo "Enhorabuena registro llevado a cabo correctamente, redireccionando ...";
                        echo "<meta http-equiv='refresh' content='8; ".Url::toRoute("site/login")."'>";
                    }
                    else
                    {
                        echo "Ha ocurrido un error al realizar el registro, redireccionando ...";
                        echo "<meta http-equiv='refresh' content='8; ".Url::toRoute("site/login")."'>";

                    }
                }
                else //Si no existe redireccionamos a login
                {
                    return $this->redirect(["site/login"]);
                }
            }
            else //Si id no es un número entero redireccionamos a login
            {
                return $this->redirect(["site/login"]);
            }
        }
    }

    public function actionRegister()
    { 

        // 


        $opciones = OpcionMenu::find()->all();
        $items = ItemMenu::find()->all();
        $subitems = SubitemMenu::find()->all();
        // 
        
        //Creamos la instancia con el model de validación
        $model = new FormRegister;

        //Mostrará un mensaje en la vista cuando el usuario se haya registrado
        $msg = null;

        //Validación mediante ajax
        if ($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax)
        {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);

        }

        if ($model->load(Yii::$app->request->post()))
        {
            
            if($model->validate())
            {

                // echo "<pre>";
                // print_r($_REQUEST);
                // die();

                //Preparamos la consulta para guardar el usuario
                $user = new Users;
                $user->username = $model->username;
                $user->email = $model->email;
                $user->role = $model->role; 
                $user->nombres = $model->nombres; 
                $user->apellidos = $model->apellidos; 
                $user->numeroIdentificacion = $model->numeroIdentificacion; 
                $user->direccion = $model->direccion; 
                $user->telefono = $model->telefono; 
                
                //Encriptamos el password
                $user->password = md5($model->password);                // $user->password = md5($model->password);
                //Creamos una cookie para autenticar al usuario cuando decida recordar la sesión, esta misma
                //clave será utilizada para activar el usuario
                $user->authKey = $this->randKey("abcdef0123456789", 200);
                //Creamos un token de acceso único para el usuario
                $user->accessToken = $this->randKey("abcdef0123456789", 200);
                //Si el registro es guardado correctamente
                if ($user->insert())
                {

                    // CREACION DEL MENU PARA EL PERFIL CREADO
                    if (isset($_POST['opciones'])) {
                        foreach ($_POST['opciones'] as $opcion) {
                            
                            $opcionExplode = explode(',', $opcion);
                            $opcion = $opcionExplode[0];
                            $item = $opcionExplode[1];
                            $subitem = $opcionExplode[2];
                            $menu = new Menuperfil();
                            $menu->usuario_idusuario = $user->id;
                            $menu->opcion = $opcion;
                            $menu->item = $item;
                            $menu->subitem = $subitem;
                            $menu->save();
                        }
                    }
                    
                    $newUser = Users::findOne($user->id);
                    $msg = "El funcionario ".$newUser->username.' ha sido registrado';
                    $alert = 'success';
                    $graphicon = 'ok';
                    return $this->render("newUser", 
                        [
                            "model" => $newUser, 
                            "msg" => $msg,
                            "alert" => $alert,
                            "graphicon" => $graphicon
                        ]
                    );
                }
                else
                {
                    print_r($user->getErrors());
                    die;
                    $newUser = false;
                    $msg = "Ha ocurrido un error al llevar a cabo tu registro";
                    $alert = 'danger';
                    $graphicon = 'remove';

                    
                }
            }
            else
            {
                $model->getErrors();

            }
        }
        $roles = Rol::find()->all();
        return $this->render("register", 
            [

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/admin.php
<h1>vista administrador</h1>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name') ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = $name;
?>


    
<div class="col-lg-12">

    <div class="jumbotron">
        <img width="150" src="<?php echo Url::base(); ?>/images/error.png" alt="..." class="">
        <br>
        <div class="alert alert-danger">
            <?= nl2br(Html::encode($message)) ?>
        </div>
        <p>
            Por favor contactese con el area de Tecnologia. Gracias
        </p>
    </div>

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    


    

        
</div>

views/site/index.php
<?php 
    use yii\helpers\Html;
    use yii\helpers\Url;
    use app\models\Users;
    use yii\bootstrap4\ActiveForm;
    // $this->title = 'Inicio';
?>
  <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <!-- /.content-header -->
  <script src="<?php echo Url::base(); ?>/librerias/jquery-3.4.1.min.js"></script>

  <script src="<?php echo Url::base(); ?>/js/highcharts.js"></script>
  <script src="<?php echo Url::base(); ?>/js/exporting.js"></script>
  <script src="<?php echo Url::base(); ?>/js/export-data.js"></script>
  <script src="<?php echo Url::base(); ?>/js/highcharts-3d.js"></script>
  <script src="<?php echo Url::base(); ?>/js/cylinder.js"></script>

<div class="row">
    <div class="col-lg-12 text-center">      
    </div>
    <!-- ./col -->
    <div class="col-lg-3 ">
      <!-- small box -->
      <div class="card card-stats">
        <div class="card-header card-header-primary card-header-icon">
          <div class="card-icon">
            <center>
              <span class="fa fa-calculator" style="width: 80px; "></span>
            </center>
          </div>
          <h5 class="card-title">Peliculas registradas</h5>
          <h3 class="card-category text-danger"><?php echo $peliculas['total']?></h3>
        </div>
        <div class="card-footer">
          <!-- <a href="<?php echo Url::base(); ?>/index.php?r=site%2Falmacenindex" class="small-box-footer">Ir al Módulo <i class="fas fa-arrow-circle-right"></i></a>         -->
          <a class="btn btn-primary btn-block" href="<?php echo Url::base(); ?>/index.php?r=peliculas%2Findex">Ir al Módulo</a>
        </div>
      </div>
    </div>
</div>

<figure class="highcharts-figure">
    <div id="container"></div>
    
</figure>

<div class="col-lg-12">
</div>



<!-- MODAL PARA REASIGNAR LA SUBACTIVIDAD -->


<!--  ========= Js ======== -->
<script>
$(document).on('click','.gestion',function(){
  $("#load").modal({
          backdrop: "static", 
          keyboard: false, 
          show: true 
      });
  });
</script>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

// $this->title = 'La Salle SG';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login"><br><br><br><br>
    <!-- <h1><?//= Html::encode($this->title) ?></h1> -->
    <div class="col-md-4 col-sm-6 ml-auto mr-auto"><!-- col-lg-4  -->
        <div class="card card-login card-hidden">
            <div class="card-header card-header-primary text-center"  data-background-color="blue">
                <h4 class="card-title">INICIO DE SESIÓN</h4>
                <div class="social-line">
                    
                </div>
            </div>
            <?php $form = ActiveForm::begin([
                    'id' => 'login-form',
//                    
                ]); ?>
            <div class="card-body ">            
                <?= $form->field($model, 'username')->textInput(['placeholder' => 'Usuario', 'class' => 'form-control'])->label(false) ?>      <br>  
                <?= $form->field($model, 'password')->passwordInput(['placeholder' => 'Contraseña', 'class' => 'form-control'])->label(false) ?><br>
                <span class="bmd-form-group">
                    <div class="input-group">
                        <?= $form->field($model, 'rememberMe')->checkbox()->label('recordarme aqui') ?><br>
                        
                    </div>
                    
                </span>
            </div>
            <div class="col-lg-12">
            <div class="input-group">
                    <?= Html::submitButton('Ingresar', ['class' => 'btn btn-default btn-block ', 'name' => 'login-button']) ?>    
                    </div>
                
            </div>
           
           <div class="card-footer">
           </div>
           <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

<?php

$this->registerJs("
    $(document).ready(function(){
        
        $('.control-label').css('font-size','12px');
    });");    
?>

views/site/loginaut.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap4\ActiveForm;

?>

<?php $form = ActiveForm::begin([
    'id' => 'login-form',
]); ?>

    <?php if (isset($msg)) { ?>
        <div class="alert alert-danger" role="alert">
            <?php echo $msg; ?>
        </div>
    <?php } ?>
    
    <div class="row justify-content-md-center form-login">
        <div class="col-md-4 col-md-auto contentLogin">
            <center>
                <br>
                <img class="img-responsive" width="50%" src="<?php echo Url::base(); ?>/images/OSA.png">
                <br>
                <br>
            </center>
            <div class="col-lg-12">
                <div class="col-lg-12 noPadding">
                    <div class="form-group has-feedback">
                        <i class="icon-key"></i>
                        <?= $form->field($model, 'autoridad_code')->Input(['placeholder' => 'Codigo de Ingreso', 'class' => 'form-control'])->label(false) ?>
                    </div>
                </div>
                <div class="form-group col-lg-12 noPadding">
                        <br>
                        <div class="col-lg-12 noPadding ol-lg-offset-2">
                            <?= Html::submitButton('Ingresar a la Plataforma', ['class' => 'btn btn-success btn-block text-bold', 'name' => 'login-button']) ?>
                        </div>
                </div>
            </div>
             <br>
             <br>
            <center>
            <p>Siguenos en:</p>
            <a target="_blank" href="https://www.facebook.com/OrganizacionSaycoAcinpro/"><i class="fab fa-facebook fa-2x"></i></a>
            </center>
            
        </div>
    </div>

<?php ActiveForm::end(); ?>

views/site/loginindex.php
<?php
    use yii\helpers\Html;
    use yii\helpers\Url;
    use yii\bootstrap4\ActiveForm;
?>
<?php $form = ActiveForm::begin([
    'id' => 'login-form',
]); ?>

    <div class="row justify-content-md-center form-login">
        <div class="col-md-4 col-md-auto contentLogin">
            <center>
                <br>
                <img class="img-responsive" width="50%" src="<?php echo Url::base(); ?>/images/OSA.png">
                <br>
                <br>
            </center>
            <div class="col-lg-12">
                <div class="col-lg-12 noPadding">
                    <div class="form-group has-feedback">
                        <?= $form->field($model, 'username')->textInput(['placeholder' => 'Usuario', 'class' => 'form-control'])->label(false) ?>
                        <i class="fas fa-user user-icon"></i>
                    </div>
                </div>
                <div class="col-lg-12 noPadding">
                    <div class="form-group has-feedback">
                        <?= $form->field($model, 'password')->passwordInput(["data-toggle"=>"password",'placeholder' => 'Contraseña', 'class' => 'form-control'])->label(false) ?>
                        <i class="fas fa-key user-icon" ></i>
                    </div>
                </div>
                <div class="form-group col-lg-12 noPadding">
                        <br>
                        <div class="col-lg-12 noPadding ol-lg-offset-2">
                            <?= Html::submitButton('Iniciar Sesión', ['class' => 'btn btn-success btn-block text-bold', 'name' => 'login-button']) ?>
                        </div>
                </div>
            </div>
                <br>
            <center>
            <p>Siguenos en:</p>
            <a target="_blank" href="https://www.facebook.com/UniLibertadores/"><i class="fab fa-facebook fa-2x"></i></a>
            </center>
            
            <?= Html::a('<i class="fas fa-home"></i> Regresar al inicio', ['site/login'], ['class' => 'btn-sm btn-block btn btn-danger', 'style' => 'margin-top:10px;']) ?>
        </div>
    </div>
<?php ActiveForm::end(); ?>

views/site/newUser.php
<?php 
	use yii\helpers\Html;
	use yii\widgets\DetailView;
	use yii\helpers\Url;
?>

<div class="alert alert-<?php echo $alert ?>" role="alert">
  <span class="fa fa-<?php echo $graphicon;  ?>" aria-hidden="true"></span>
  <?php echo $msg; ?>
</div>
<?php if ($model) { ?>
	<div class="users-view">

	    <!-- <h1><?= Html::encode($this->title) ?></h1> -->
	    <center>
		<div class="jumbotron">
	        <img width="150" src="<?php echo Url::base(); ?>/images/fotos/<?php echo $model->foto; ?>" alt="..." class="img-circle">
	        <p class="lead" style="color:#ffffff"><?php echo $model->nombres.' '.$model->apellidos; ?></p>
	    </div>
		</center>


	    <!-- informacion personal -->
	    <div class="card card-secondary">
	        <div class="card-header">Informacion personal</div>
	        <div class="card-body">
	            <table class="table table-striped">
	                <tbody>
	                  <tr>
	                    <td><strong>Nombres: </strong><?php echo $model->nombres; ?></td>
	                    <td><strong>Apellidos: </strong><?php echo $model->apellidos; ?></td>
	                  </tr>
	                  <tr>
	                    <td><strong>Tipo de estado: </strong><?php echo $model->numeroIdentificacion; ?></td>
	                  </tr>
	                  <tr>
	                    <!-- <td><strong>Direccion: </strong><?php echo $model->direccion; ?></td> -->
	                    <!-- <td><strong>Telefono: </strong><?php echo $model->telefono; ?></td> -->
	                  </tr>
	                  <tr>
	                    <td colspan="2"><strong>Email: </strong><?php echo $model->email; ?></td>
	                  </tr>
	                </tbody>
	              </table>
	        </div>
	    </div>

	    <!-- informacion laboral -->
	    
		<table class="table table-striped">
			<tbody>
				<tr>
				<td><strong>Username: </strong><?php echo $model->username; ?></td>
				<td><strong>Rol usuario: </strong><?php echo $model->rol->nombre; ?></td>
				</tr>
			</tbody>
		</table>
	        
	    <p>
	        <?= Html::a('<i class="fa fa-fw fa-edit"></i> Actualizar información', ['users/update', 'id' => $model->id], ['class' => 'btn btn-primary btn-sm']) ?>
	        <?= Html::a('<i class="fa fa-fw fa-plus"></i> Registrar otro funcionario', ['site/register'], ['class' => 'btn btn-primary btn-sm']) ?>
	        <?= Html::a('<i class="fa fa-fw fa-reply"></i> Volver', ['site/index'], ['class' => 'btn btn-primary btn-sm']) ?>
	    </p> 
	</div>

<?php }else{ ?>
	<p>
		<?= Html::a('<i class="fa fa-fw fa-plus"></i> Registrar otro funcionario', ['site/register'], ['class' => 'btn btn-primary btn-sm']) ?>
		<?= Html::a('<i class="fa fa-fw fa-reply"></i> Volver', ['site/index'], ['class' => 'btn btn-primary btn-sm']) ?>	
	</p> 
<?php } ?>

views/site/recoverpass.php
<?php
use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
?>
 

 

<?php $form = ActiveForm::begin([
    'method' => 'post',
    'enableClientValidation' => true,
]);
?>
<div class="card col-lg-12 container-fluid">
    <div class="card-body">

        <h3><?= $msg ?></h3>

        <div class="row justify-content-md-center form-login">
            <div class="col-md-4 col-md-auto contentLogin">
                <center>        
                    <h1>Recuperar Contraseña</h1>
                    <h1 style="font-size: 55px; margin-top: 35px; margin-bottom: 30px;" class="text-success text-bold">OSA <span style="color: black; font-size: 25px; margin-left: -20px;">Virtual</span> </h1>
                </center>
                <div class="form-group">
                    <div class="alert alert-primary" role="alert">
                        <p>Por favor ingrese el Correo electronico con el que se registro</p>                
                    </div>
                    <?= $form->field($model, "email")->input("email")->label('Correo Electronico') ?>
                </div>
                    <?= Html::submitButton("Recuperar contraseña", ["class" => "btn btn-success"]) ?>
                <?php $form->end() ?>
                <?= Html::a('Regresar', ['site/login'], ['class' => 'btn btn-danger']) ?>
            </div>
        </div>
    </div>
</div>

views/site/resetpass.php
<?php
use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
?>
 
<?php $form = ActiveForm::begin([
    'method' => 'post',
    'enableClientValidation' => true,
]);
?>

<div class="card col-lg-12 container-fluid">
    <div class="card-body">

        <h3><?= $msg ?></h3>
        <div class="row justify-content-md-center form-login">
            <div class="col-md-4 col-md-auto contentLogin">

                <center>        
                    <h1>Resetear Contraseña</h1>
                </center> <br>
                <div class="form-group">
                <?= $form->field($model, "email")->input("email") ?>  
                </div>
                
                <div class="form-group">
                <?= $form->field($model, "password")->input("password") ?>  
                </div>
                
                <div class="form-group">
                <?= $form->field($model, "password_repeat")->input("password") ?>  
                </div>

                <div class="form-group">
                <?= $form->field($model, "verification_code")->input("text") ?>  
                </div>

                <div class="form-group">
                <?= $form->field($model, "recover")->input("hidden")->label(false) ?>  
                </div>
                
                <?= Html::submitButton("Reset password", ["class" => "btn btn-primary"]) ?>
                <?php $form->end() ?>
            </div>
        </div>
    </div>
</div>

views/site/user.php
<h1>vista user normal</h1>
<?php echo 'asdfasdf'; ?>