models/ItemMenu.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "item_menu".
 *
 * @property integer $id
 * @property string $action
 * @property string $etiqueta
 * @property integer $id_opcion
 * @property integer $estado
 * @property integer $orden
 *
 * @property OpcionMenu $idOpcion
 */
class ItemMenu extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item_menu';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_opcion'], 'integer'],
            [['action', 'etiqueta'], 'string', 'max' => 45],
            [['id_opcion'], 'exist', 'skipOnError' => true, 'targetClass' => OpcionMenu::className(), 'targetAttribute' => ['id_opcion' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'action' => 'Action',
            'etiqueta' => 'Etiqueta',
            'id_opcion' => 'Id Opcion',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdOpcion()
    {
        return $this->hasOne(OpcionMenu::className(), ['id' => 'id_opcion']);
    }
}

controllers/ItemmenuController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ItemMenu;
use app\models\ItemMenuSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ItemmenuController implements the CRUD actions for ItemMenu model.
 */
class ItemmenuController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ItemMenu models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ItemMenuSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ItemMenu model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ItemMenu model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ItemMenu();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing ItemMenu model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing ItemMenu model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ItemMenu model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ItemMenu the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ItemMenu::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/itemmenu/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\OpcionMenu;

/* @var $this yii\web\View */
/* @var $model app\models\ItemMenu */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="item-menu-form">

    <?php $form = ActiveForm::begin(); ?>
    <!-- ============== informacion personal -->
    <div class="card card-secondary">
        <div class="card-header card-header-primary">
            <h3 class="card-title">Información de la aplicación </h3>
        </div>
        <!-- /.card-header -->
        <!-- card body -->
        <div class="card-body">
            <div class="row">
                <div class="col-lg-12 ">
                    <div class="row">

                        <div class="col-lg-6">
                            <?= $form->field($model, 'etiqueta')->textInput(['maxlength' => true]) ?>        
                        </div>
                        <div class="col-lg-6">
                            <?= $form->field($model, 'action')->textInput(['maxlength' => true]) ?>        
                        </div>
                    </div>

                </div>
                <div class="col-lg-12 ">
                    <div class="row">

                    
                        <div class="col-lg-6">
                            <?= Html::label('Opcion', 'id_opcion', ['class'=>'control-label']) ?>
                            <?= Html::activeDropDownList(
                                $model,
                                'id_opcion',
                                ArrayHelper::map(OpcionMenu::find()
                                        ->all(), 'id', 'nombre'),
                                [
                                    'class'=>'form-control',
                                    'prompt'=>'[-- Seleccione Opcion --]',
                                    'value'=> '',
                                    'required' => 'required'
                                ]) 
                            ?>
                            <div class="help-block"></div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <br><?= Html::submitButton($model->isNewRecord ? 'Registrar' : 'Actualizar', ['class' => $model->isNewRecord ? 'btn btn-default btn-sm' : 'btn btn-default btn-sm']) ?>
                    <?= Html::a('<i class="fa fa-fw fa-reply"></i> Volver', ['itemmenu/index'], ['class' => 'btn btn-primary btn-sm']) ?>
                </div>
            </div>
        </div>

    </div>

    <?php ActiveForm::end(); ?>

</div>

views/itemmenu/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ItemMenuSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="item-menu-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'action') ?>

    <?= $form->field($model, 'etiqueta') ?>

    <?= $form->field($model, 'id_opcion') ?>

    <?= $form->field($model, 'estado') ?>

    <?php // echo $form->field($model, 'orden') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/itemmenu/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\ItemMenu */

$this->title = 'Registro de Item Menu';
$this->params['breadcrumbs'][] = ['label' => 'Item Menus', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="item-menu-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/itemmenu/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ItemMenuSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Sub - Menus';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="item-menu-index">
   
    
    <div class="card card-primary">
        <!-- Default card contents -->
        <div class="card-header card-header-primary">ITEM MENÚ</div>
        <div class="card-body">
            <p>
                <?= Html::a("<i class='fa fa-check'></i> &nbsp; Crear Item", ['create'], ['class' => 'btn btn-default']) ?>
            </p>

            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    // 'id',
                    'action',
                    'etiqueta',
                    // 'id_opcion',

                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{view}{update}',
                        'buttons' => [
                            
                            'view' => function ($url, $model, $key) {
                                // return Html::a('My Action', ['my-action', 'id'=>$model->id]);
                                return Html::a('<span class="fas fa-eye"></span>', ['itemmenu/view', 'id'=>$model->id] );
                            },

                            'update' => function ($url, $model, $key) {
                                // return Html::a('My Action', ['my-action', 'id'=>$model->id]);
                                return Html::a('<span class="fas fa-user-edit"></span>', ['itemmenu/update', 'id'=>$model->id] );
                            },
                        ]
                    ],  
                ],
            ]); ?>
        </div>
    </div>
        
</div>

views/itemmenu/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ItemMenu */

$this->title = 'Atualización';
$this->params['breadcrumbs'][] = ['label' => 'Item Menus', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="item-menu-update">

    <h3 style="color:#ffffff"><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/itemmenu/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\ItemMenu */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Item Menus', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="item-menu-view">
    <div class="card card-primary">
        <!-- Default card contents -->
        <div class="card-header card-header-primary">ITEM MENÚ</div>
        <div class="card-body">

            <p>
                <?= Html::a('<i class="fa fa-fw fa-edit"></i> Actualizar información', ['update', 'id' => $model->id], ['class' => 'btn btn-default']) ?>
                <?= Html::a('<i class="fa fa-fw fa-reply"></i> Volver', ['itemmenu/index'], ['class' => 'btn btn-primary btn-sm']) ?>
            </p>

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'id',
                    'action',
                    'etiqueta',
                    'id_opcion',
                ],
            ]) ?>
        </div>
    </div>
</div>