models/User.php
<?php

namespace app\models;

class User extends \yii\base\BaseObject implements \yii\web\IdentityInterface
{
    
    public $id;
    public $username;
    public $email;
    public $password;
    public $authKey;
    public $accessToken;
    public $activate;
    public $role;
    public $foto;
    public $nombres;
    public $apellidos;
    public $numeroIdentificacion;
    public $direccion;
    public $telefono;
    
    


    // ========== Validacion rol administrador
    public static function isUserAdmin($id)
    {
       if (Users::findOne(['id' => $id, 'activate' => '1', 'role' => 1])){
        return true;
       } else {

        return false;
       }

    }


    // ========== Validacion rol Almacen
    public static function isUserAlmacen($id)
    {
         $userIdentity = Users::findOne($id);
         $arrayRole = explode(',', $userIdentity->role);

        if (Users::findOne(['id' => $id, 'activate' => '1'])){
        
             if (in_array(5, $arrayRole)) {
                 return true;
             }else{
                 return false;
             }

        } else {
         return false;
        }
    }
    
    // ========== Validacion rol Compras
    public static function isCompras($id)
    {
        $userIdentity = Users::findOne($id);
        $arrayRole = explode(',', $userIdentity->role);

        if (Users::findOne(['id' => $id, 'activate' => '1'])){
        
            if (in_array(16, $arrayRole)) {
                return true;
            }else{
                return false;
            }

        } else {
        return false;
        }
    }


    // ========== Validacion rol Compras
    public static function isJefes($id)
    {
        $userIdentity = Users::findOne($id);
        $arrayRole = explode(',', $userIdentity->role);

        if (Users::findOne(['id' => $id, 'activate' => '1'])){
        
            if (in_array(17, $arrayRole)) {
                return true;
            }else{
                return false;
            }

        } else {
        return false;
        }
    }
    


    /* busca la identidad del usuario a través de su $id */

    public static function findIdentity($id)
    {
        $user = Users::find()
                ->where("activate=:activate", [":activate" => 1])
                ->andWhere("id=:id", ["id" => $id])
                ->one();
        // echo "<pre>";
        // print_r($user);
        // die;
        return isset($user) ? new static($user) : null;
    }

    /**
     * @inheritdoc
     */
    
    /* Busca la identidad del usuario a través de su token de acceso */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        
        $users = Users::find()
                ->where("activate=:activate", [":activate" => 1])
                ->andWhere("accessToken=:accessToken", [":accessToken" => $token])
                ->all();
        
        foreach ($users as $user) {
            if ($user->accessToken === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param  string      $username
     * @return static|null
     */
    
    /* Busca la identidad del usuario a través del username */
    public static function findByUsername($username)
    {
        $users = Users::find()
                ->where("activate=:activate", ["activate" => 1])
                ->andWhere("username=:username", [":username" => $username])
                ->all();
        
        foreach ($users as $user) {
            if (strcasecmp($user->username, $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * @inheritdoc
     */
    
    /* Regresa el id del usuario */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    
    /* Regresa la clave de autenticación */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    
    /* Valida la clave de autenticación */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param  string  $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        /* Valida el password */
        if (crypt($password, $this->password) == $this->password)
        {
        return $password === $password;
        }
    }
}

models/Users.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "users".
 *
 * @property integer $id
 * @property string $username
 * @property string $email
 * @property string $password
 * @property string $authKey
 * @property string $accessToken
 * @property integer $activate
 * @property integer $role
 * @property integer $cargo_id
 * @property string $nombres
 * @property string $apellidos
 * @property string $foto
 */
class Users extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombres', 'apellidos', 'numeroIdentificacion' ,'username','role' ,'password'], 'required'],
            [['activate','numeroIdentificacion'], 'integer'],
            [['foto','role'], 'string'],
            [['username'], 'string', 'max' => 50],
            [['email'], 'string', 'max' => 80],
            [['email'], 'email'],
            [['password', 'authKey', 'accessToken'], 'string', 'max' => 250],
            [['direccion'], 'string', 'max' => 150],
            // ['password', 'match', 'pattern' => "/^.{6,20}$/", 'message' => 'Mínimo 6 y máximo 16 caracteres'],
            [['nombres', 'apellidos'], 'string', 'max' => 60],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'email' => 'Email',
            'password' => 'Password',
            'authKey' => 'Auth Key',
            'accessToken' => 'Access Token',
            'activate' => 'Activate',
            'role' => 'Role',
            'nombres' => 'Nombres',
            'apellidos' => 'Apellidos',
            'foto' => 'Foto',
        ];
    }

    public function getRol()
    {
        return $this->hasOne(Rol::className(), ['id' => 'role']);
    }

    

    

    
    

    public function email_existe($attribute, $params)
    {
    
    //Buscar el email en la tabla
    $table = Users::find()->where("email=:email", [":email" => $this->email]);
    
    //Si el email existe mostrar el error
    if ($table->count() == 1)
    {
      $this->addError($attribute, "El email seleccionado existe");
    }
      }
    
      public function username_existe($attribute, $params)
      {
    //Buscar el username en la tabla
    $table = Users::find()->where("username=:username", [":username" => $this->username]);
    
    //Si el username existe mostrar el error
    if ($table->count() == 1)
    {
                  $this->addError($attribute, "El usuario seleccionado existe");
    }
      }
    
}

controllers/UsersController.php
<?php

namespace app\controllers;

use Yii;
use yii\db\Query;
use app\models\Rol;
use app\models\User;
use app\models\Users;
use yii\web\Controller;
use app\models\ItemMenu;
use app\models\Menuperfil;
use app\models\OpcionMenu;

use app\models\Extensiones;
use app\models\SubitemMenu;
use app\models\UsersSearch;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\UsersDocumentos;
use yii\web\NotFoundHttpException;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','update','delete','view'],
                'rules' => [
                    // Acciones rol ADMINISTRADOR
                    [
                        'actions' => ['index', 'update','view'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserAdmin(Yii::$app->user->identity->id);
                        },
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        // $model = Users::find()->joinWith('rol')->all();
        $query = new Query();
        $connection = Yii::$app->db;
        $query = $connection->createCommand('SELECT     *, users.id as usuario
                                                from    users
                                                        join rol on (role = rol.id)
                                                where   1=1
                                            ');
        $model = $query->queryAll();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model,
        ]);
    }


    public function actionInactivar($id){

        $query = new Query();
        $connection = Yii::$app->db;

        // echo "<pre>";
        // print_r($_REQUEST);
        // die;
        
        $query = $connection->createCommand('UPDATE users
                                                SET activate = 0 
                                                where   id = '.$id.''
                                                            )->execute();
        // die;
        return $this->redirect(['index']);
    }

    public function actionActivar($id){

        $query = new Query();
        $connection = Yii::$app->db;

        // echo "<pre>";
        // print_r($_REQUEST);
        // die;
        
        $query = $connection->createCommand('UPDATE users
                                                SET activate = 1 
                                                where   id = '.$id.''
                                                                )->execute();
        // die;
        return $this->redirect(['index']);
    }

    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   

        $documentos = UsersDocumentos::find()->where(['user_documento_cliente_id' => $id])->all();
        $documentosextension = UsersDocumentos::find()->where(['user_documento_cliente_id' => $id])->groupBy('user_documento_tipo_archivo')->all();

        return $this->render('view', [
            'model' => $this->findModel($id),
            'documentos' => $documentos,
            'documentosextension' => $documentosextension,
            'modelDocumento' => new UsersDocumentos(),
        ]);
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        // 
        $roles = Rol::find()->all();
        $menuperfil = MenuPerfil::find()->where(['usuario_idusuario' => $id])->all();
        
        $useropcion = array();
        $useritem = array();
        $usersubitem = array();

        if ($menuperfil) {
            foreach ($menuperfil as $m) {
                // OPCION
                if ($m->opcion && !$m->item && !$m->subitem) {
                    array_push($useropcion, $m->opcion);
                }
                // ITEM
                if ($m->opcion && $m->item && !$m->subitem) {
                    array_push($useritem, $m->item);
                }
                // SUBITEM
                if ($m->opcion && $m->item && $m->subitem) {
                    array_push($usersubitem, $m->subitem);
                }
            }
        }


        $opciones = OpcionMenu::find()->all();
        $items = ItemMenu::find()->all();
        $subitems = SubitemMenu::find()->all();
        // 
        
        if (yii::$app->user->identity->role == 1) {
            $model = $this->findModel($id);
            $actualPassword = $model->password;


            
            if ($model->load(Yii::$app->request->post())) {


                // echo "<pre>";
                // print_r($_REQUEST);
                // die;
                
                // if (isset($_REQUEST['Users']['fechaInicioContrato'])) {
                //     $model->fechaInicioContrato = $_REQUEST['Users']['fechaInicioContrato'];
                    
                // }
                // if (isset($_REQUEST['Users']['fechaFinalContrato'])) {
                //     $model->fechaFinalContrato = $_REQUEST['Users']['fechaFinalContrato'];
                    
                // }

                // if ($_REQUEST['Users']['tipoContrato']=="") {
                //     $model->tipoContrato = 497;
                // }

                // ELIMINAR LOS MENUS ASOCIADOS ANTERIORMENTE
                Menuperfil::deleteAll(['usuario_idusuario' => $id]);
                // CREACION DEL MENU PARA EL PERFIL CREADO
                if (isset($_POST['opciones'])) {
                    foreach ($_POST['opciones'] as $opcion) {
                        
                        $opcionExplode = explode(',', $opcion);
                        $opcion = $opcionExplode[0];
                        $item = $opcionExplode[1];
                        $subitem = $opcionExplode[2];

                        $menu = new Menuperfil();
                        $menu->usuario_idusuario = $id;
                        $menu->opcion = $opcion;
                        $menu->item = $item;
                        $menu->subitem = $subitem;
                        $menu->save();

                    }
                }





                if ($actualPassword != $model->password) {
                    $model->password = crypt($model->password, Yii::$app->params["salt"]);
                }
                if ($model->save()) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            } else {
                
                return $this->render('update', [
                    'model' => $model,
                    'menuperfil' => $menuperfil,
                    'useropcion' => $useropcion,
                    'useritem' => $useritem,
                    'usersubitem' => $usersubitem,
                    'opciones' => $opciones,
                    'items' => $items,
                    'subitems' => $subitems,
                ]);
            }
        }else{



            if (yii::$app->user->identity->id == $id) {
                $model = $this->findModel($id);
                    $actualPassword = $model->password;
                    if ($model->load(Yii::$app->request->post())) {
                        if ($actualPassword != $model->password) {
                            $model->password = crypt($model->password, Yii::$app->params["salt"]);
                        }
                        if ($model->save()) {
                            return $this->redirect(['view', 'id' => $model->id]);
                        }
                    } else {
                        return $this->render('update', [
                            'model' => $model,
                            'menuperfil' => $menuperfil,
                            'useropcion' => $useropcion,
                            'useritem' => $useritem,
                            'usersubitem' => $usersubitem,
                            'opciones' => $opciones,
                            'items' => $items,
                            'subitems' => $subitems,
                        ]);
                    }
                }else{
                    $model = $this->findModel(yii::$app->user->identity->id);
                    
                    return $this->render('update', [
                        'model' => $model,
                    ]);
                }
            }

        }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionUploadfiles()
    {
        // echo "<pre>";

views/users/_form.php
<?php

use app\models\Cargos;
use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Rol;
use app\models\TiposDetalles;
use kartik\date\DatePicker;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-form">

    <?php $form = ActiveForm::begin(); ?>


    <!-- ============== informacion personal -->
    <div class="card card-secondary">
      <div class="card-header card-header-primary">
        <h3 class="card-title">Información Personal</h3>
      </div>
      <!-- /.card-header -->
      <!-- card body -->
      <div class="card-body">
        <div class="row">
          
          <div class="col-lg-6 form-group">
            <?= $form->field($model, "nombres") ?>   
          </div>
          <div class="col-lg-6 form-group">
            <?= $form->field($model, "apellidos") ?>   
          </div>
        
        
          <!-- <div class="col-lg-6 form-group">
            <?php if ($model->isNewRecord) { ?>
              <?= $form->field($model, "numeroIdentificacion") ?>  
            <?php }else{ ?>
              <?= $form->field($model, "numeroIdentificacion") ?>  
            <?php } ?> 
          </div> -->
        
        
          <div class="col-lg-6 form-group">
            <?= $form->field($model, "direccion") ?>   
          </div> 

           <div class="col-lg-6 form-group">
            <?= $form->field($model, "telefono") ?>   
          </div>
        
        
          <div class="col-lg-6 form-group">
              <?= $form->field($model, "email")->input("email") ?>   
          </div>
          
        
        
          
          
        </div>
      </div>
    </div>
    <!-- ============== informacion laboral -->
    <div class="card">
      <div class="card-header card-header-primary">
        <h3 class="card-title">Información del Usuario </h3>
      </div>
      <!-- /.card-header -->
      <!-- card body -->
      <div class="card-body">
        <div class="row">
            
          <div class="col-lg-6 form-group">
            <?= $form->field($model, 'username') ?>

          </div>

          <div class="col-lg-6 form-group">
              <?= $form->field($model, "password")->input("password") ?>   
          </div>



          <div class="col-lg-6 form-group">
            

            <!-- <?= Html::label('Rol Usuario', 'tipoContrato', ['class'=>'control-label']) ?> -->
            <?php
            
              $var = \yii\helpers\ArrayHelper::map(Rol::find()->all(), 'id', 'nombre');
              echo $form->field($model, 'role')->dropDownList($var, ['prompt' => 'Seleccione uno', 'class' => 'form-control select2bs4'])->label('Rol Usuario'); 
            ?>

          </div>
      
      
          <div class="col-lg-6 form-group">
              <?php 
                  $var = [  1 => 'Activo',  0 => 'Inactivo'];
                  echo $form->field($model, 'activate')->dropDownList($var, ['prompt' => 'Seleccione uno', 'class' => 'form-control select2bs4'])->label('Estado Usuario'); 
              ?>
          </div>
          
          
          
          
        </div>
      </div>
    </div>
    <!-- ============== MENU ASOCIADO AL PERFIL ============ -->
    
    <div class="card card-secondary " id="demo">
      <div class="card-header card-header-primary">Menus Asociados al perfil</div>
      <div class="card-body">
            <div class="checkbox pull-right">
              <label><input  type="checkbox"  checked  id="selectAll" ><strong>Seleccionar todo</strong></label>
            </div>
        <br>
        <br>
        <?php foreach ($opciones as $o) { ?>
          <div class="checkbox">
            <?php if (in_array($o->id,$useropcion)) { ?>
              <?php $checkedOpcion = 'checked'; ?>
            <?php }else{ ?>
              <?php $checkedOpcion = ''; ?>
            <?php } ?>
            <label><input class="opcionesCheck"  type="checkbox" name="opciones[]" value="<?php echo $o->id.',0,0' ?>" <?php echo $checkedOpcion; ?>  id="<?php echo $o->id; ?>" value=""><?php echo $o->nombre; ?></label>
          </div>
          <div style="margin-left: 20px;">
            <?php foreach ($items as $i) { ?>
              <?php if ($o->id == $i->id_opcion) { ?>
                <div class="checkbox">
                  <?php if (in_array($i->id,$useritem)) { ?>
                    <?php $checkedItem = 'checked'; ?>
                  <?php }else{ ?>
                    <?php $checkedItem = ''; ?>
                  <?php } ?>
                  <label><input type="checkbox" name="opciones[]" value="<?php echo $o->id.','.$i->id.',0' ?>" class="itemsCheck" id="<?php echo $i->id; ?>" <?php echo $checkedItem; ?>  data-opcion="<?php echo $o->id; ?>" value=""><?php echo $i->etiqueta; ?></label>
                </div>

                <div style="margin-left: 20px;">
                  <?php foreach ($subitems as $s) { ?>
                    <?php if ($i->id == $s->id_item) { ?>
                      <div class="checkbox">
                        <?php if (in_array($s->id,$usersubitem)) { ?>
                          <?php $checkedSubitem = 'checked'; ?>
                        <?php }else{ ?>
                          <?php $checkedSubitem = ''; ?>
                        <?php } ?>
                        <label><input type="checkbox" name="opciones[]" value="<?php echo $o->id.','.$i->id.','.$s->id ?>" class="subitemsCheck" <?php echo $checkedSubitem; ?>  data-opcion="<?php echo $o->id; ?>" data-item="<?php echo $i->id; ?>"><?php echo $s->etiqueta; ?></label>
                      </div>
                    <?php } ?>
                  <?php } ?>
                </div>
              <?php } ?>
            <?php } ?>
          </div>
        <?php } ?>
      </div>
    </div>

    <div class="col-lg-12 noPadding form-group">
      <!-- <button type="button" class="btn btn-dark " data-toggle="collapse" data-target="#demo"><i class="fa fa-folder-open"></i>Menu</button> -->
      <?= Html::submitButton($model->isNewRecord ? 'Crear Usuario' : '<i class="fa fa-fw fa-edit"></i> Editar Usuario', ['class' => $model->isNewRecord ? 'btn btn-default btn-sm' : 'btn btn-default btn-sm', ]) ?>
      <?= Html::a('<i class="fa fa-fw fa-reply"></i> Volver', ['index'], ['class' => 'btn btn-primary btn-sm ']) ?>
      
             
    </div>

    

    <?php ActiveForm::end(); ?>

</div>
<!-- ================ JS =========== -->
<script>
  $(document).ready(function(){


    function Validar(){


    }

    $(".opcionesCheck").click(function(){
      if (!$(this).is(':checked')) {
        $(document).find("[data-opcion='" + $(this).attr('id') + "']").prop('checked', false);   
      }
    });

    $(".itemsCheck").click(function(){
      if (!$(this).is(':checked')) {
        $(document).find("[data-item='" + $(this).attr('id') + "']").prop('checked', false);   
      }else{
        $('#'+$(this).data('opcion')).prop('checked', true);
      }
    }); 

    $(".subitemsCheck").click(function(){
      if ($(this).is(':checked')) {
        $('#'+$(this).data('opcion')).prop('checked', true);
        $('#'+$(this).data('item')).prop('checked', true);
      }
    });

    $("#selectAll").click(function(){
      if ($(this).is(':checked')) {
        $(".opcionesCheck").prop('checked', true);
        $(".itemsCheck").prop('checked', true);
        $(".subitemsCheck").prop('checked', true);
      }else{
        $(".opcionesCheck").prop('checked', false);
        $(".itemsCheck").prop('checked', false);
        $(".subitemsCheck").prop('checked', false);
      }
    });

    $(".addRole").click(function(){
      if ($(this).hasClass('select')) {
        $(this).removeClass('select');
        $(this).addClass('btn-primary');
        $(this).removeClass('btn-success');
      }else{
        $(this).addClass('btn-success');
        $(this).addClass('select')
        $(this).removeClass('btn-primary');
      }
      validateRoleActive();
    });
  })
  // =============== FUNCIONES ==================
  function validateRoleActive(){
    var concatRole = '';
    var init = false;
    $(".addRole").each(function(){
      console.log($(this).attr('class'));
      if ($(this).hasClass('select')) {
        if (init) {
          concatRole = concatRole + ',' + $(this).attr('id');
        }else{
          concatRole = $(this).attr('id');
          init = true;
        }
      }
    });
    $("#users-role").val(concatRole);
  }
</script>

views/users/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Create Users';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/users/index.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;

$this->title = 'Usuarios del Sistema';
$this->params['breadcrumbs'][] = $this->title;
?>
<script src="<?php echo Url::base(); ?>/librerias/jquery-3.4.1.min.js"></script>
    <!-- /.card-header -->
<div class="users-index">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h3 class="card-title"><?php echo $this->title; ?></h3>
                <!--<h4 class="card-category">New employees on 15th September, 2016</h4>-->
            </div>
            <div class="card-body table-responsive">
                <div class="box-tools ">
                    <p>
                        <?= Html::a("<i class='fa fa-user'></i> &nbsp;Crear Usuario", ['site/register'], ['class' => 'btn btn-default']) ?>  
                    </p>
                </div>        
                <div class="col-lg-12">
                    <div class="row">
                    <div class="table-responsive">
                        <table id="example1" class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                            <th>Username</th>
                            <th>nombres</th>
                            <th>apellidos</th>
                            <th>No. identificación</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th>Dirección</th>
                            <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($model as $key => $value) { ?>
                            <tr>
                                <td><?php echo $value['username'] ?></td>
                                <td><?php echo $value['nombres'] ?></td>
                                <td><?php echo $value['apellidos'] ?></td>
                                <td><?php echo $value['numeroIdentificacion'] ?></td>
                                <td><?php echo $value['email'] ?></td>
                                <td><?php echo strtoupper( $value['nombre']) ?></td>
                                <td><?php echo $value['direccion'] ?></td>
                                <td>
                                    <?= Html::a('<i class="fa fa-fw fa-eye"></i> Ver', ['users/view', 'id'=> $value['usuario']], ['class' => 'btn btn-primary btn-block btn-xs ']) ?>
                                    <?= Html::a('<i class="fa fa-fw fa-edit"></i> Editar', ['users/update', 'id'=> $value['usuario']], ['class' => 'btn btn-primary btn-block btn-xs text-white ']) ?>
                                <?php if ($value['activate']==1) { ?>
                                    <?= Html::a('<i class="fa fa-fw fa-trash"></i> Inactivar', ['users/inactivar', 'id'=> $value['usuario']], ['class' => 'btn btn-danger btn-block btn-xs text-white ']) ?>
                                <?php }else{ ?>
                                    <?= Html::a('<i class="fa fa-fw fa-check "></i> Activar', ['users/activar', 'id'=> $value['usuario']], ['class' => 'btn btn-success btn-block btn-xs text-white ']) ?>
                                <?php } ?>
                                </td>
                            </tr>
                            <?php } ?>
                        </tbody>
                        </table>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<script>
  $(function () {
    $("#example1").DataTable({
    
    language: {
      "processing": "Procesando...",
      "lengthMenu": "Mostrar _MENU_ registros",
      "zeroRecords": "No se encontraron resultados",
      "emptyTable": "Ningún dato disponible en esta tabla",
      "info":           "Mostrando _START_ a _END_ de _TOTAL_ Elementos",
      "infoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
      "infoFiltered": "(filtrado de un total de _MAX_ registros)",
      "search": "Buscar:",
      "infoThousands": ",",
      "loadingRecords": "Cargando...",
      "paginate": {
          "first": "Primero",
          "last": "Último",
          "next": "Siguiente",
          "previous": "Anterior"
      },
      "aria": {
          "sortAscending": ": Activar para ordenar la columna de manera ascendente",
          "sortDescending": ": Activar para ordenar la columna de manera descendente"
      },
        
        
    },
      "responsive": true, "lengthChange": true, "autoWidth": false,
      // "dom": 'Bfrtip',
      "buttons": [
            {
                "extend": 'copyHtml5',
                "exportOptions": {
                    "columns": [ 0, ,1,2,3,4,5,6 ]
                }
            },
            {
                "extend": 'excelHtml5',
                "exportOptions": {
                    "columns": [0,1,2,3,4,5,6]
                }
            },
            {
                "extend": 'pdfHtml5',
                "exportOptions": {
                    "columns": [ 0, 1, 2, 3,4,5,6 ]
                }
            },
            // 'colvis'
        ]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');


    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>